title: qrandom.lumii.lv
email: krisjanis.petrucena@lumii.lv
description: >- # this means to ignore newlines until "baseurl:"
  The QRNG service project is a designed to serve as an alternative to /dev/random.
  The project is composed of a character device /dev/qrandom0 and a userspace service working together to provide a reliable source of random bytes.
  The userspace service can fetch random bytes from a remote Quantum Random Number Generator (QRNG) offered by qrng.lumii.lv.
  It's also adaptable to cater to other requirements based on your project's needs.
baseurl: "/qrandom.lumii.lv/" # the subpath of your site, e.g. /blog
url: "https://krisjanisp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: LUMII-Syslab
theme: minima
header_pages:

